Models/ErrorViewModel.cs
namespace FoodApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Food.cs
namespace FoodApp.Models
{
    public class Food
    {
        public int Id { get; set; }
        public string? FoodName { get; set; }
        public string? FoodImg { get; set; }
        public string? FoodDesc { get; set; }
        public decimal? FoodCost { get; set; }
        public decimal? FoodCal { get; set; }
    }
}

Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodApp.Data;
using FoodApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace FoodApp.Controllers
{
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodsController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Foods/CalculateBMR/
        public async Task<IActionResult> BMRForm() 
        {
            return View("BMRForm");
        }
        // GET: Foods/BMRCalculated/
        public async Task<IActionResult> BMRCalculated(string gender, double weight, double height, double age) 
        {
            double bmrRes;

            if (gender == "Male") 
            {
                bmrRes = 66 + (13.7 * weight) + (5 * height) - (6.8 * age);
            }
            else
            {
                bmrRes = 665 + (9.6 * weight) + (1.8 * height) - (4.7 * age);
            }

            ViewBag.Weight = weight;
            ViewBag.Height = height;
            ViewBag.Age = age;
            ViewBag.Gender = gender;
            ViewBag.Result = $"พลังงานที่จำเป็นในแต่ละวันของคุณคือ {bmrRes} kcal";
            //int eatKcal = (int)bmrRes / 3;

            return View("BMRResult", await _context.Food.Where(f => f.FoodCal.Value < ((int)bmrRes / 3)).ToListAsync());
        }


        // GET: Foods/RandomFood/
        public async Task<IActionResult> RandomFood()
        {
            var randFood = new List<string>();
            randFood.Add("ข้าว");
            randFood.Add("ปู");
            randFood.Add("เนื้อ");
            randFood.Add("กะเพรา");
            randFood.Add("ด้ง");

            Random rnd = new Random();
            ViewBag.RandomValue = randFood[rnd.Next(0,randFood.Count)];

            return View("RandomFood");
        }

        // POST: Foods/Result/
        public async Task<IActionResult> RandomResult(string randomPhrase) 
        {
            return View("RandomResult", await _context.Food.Where(f => f.FoodName.Contains(randomPhrase)).ToListAsync());
        }

        // GET: Foods
        public async Task<IActionResult> Index()
        {

              return _context.Food != null ? 
                          View(await _context.Food.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Food'  is null.");
        }

        // GET: Foods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Food == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Foods/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FoodName,FoodImg,FoodDesc,FoodCost,FoodCal")] Food food)
        {
            if (ModelState.IsValid)
            {
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Food == null)
            {
                return NotFound();
            }

            var food = await _context.Food.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FoodName,FoodImg,FoodDesc,FoodCost,FoodCal")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Food == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Foods/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Food == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Food'  is null.");
            }
            var food = await _context.Food.FindAsync(id);
            if (food != null)
            {
                _context.Food.Remove(food);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
          return (_context.Food?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using FoodApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FoodApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Foods/BMRForm.cshtml
@{
	ViewData["Title"] = "BMR Calculator";
}

<h1 class="text-center"> คำนวณค่า BMR </h1>

<div class="row">
    <div class="d-flex justify-content-center">
		<div class="col-5">
		    <form asp-action="BMRCalculated">
                <div class="mb-3">
                    <select class="form-select" name="gender" id="userGender">
                      <option selected> ระบุเพศของคุณ </option>
                      <option value="Male"> ผู้ชาย </option>
                      <option value="Female"> ผู้หญิง </option>
                    </select>
                </div>
                <div class="mb-3">
                    <label for="userWeight" class="form-label">น้ำหนัก (kg)</label>
                    <input type="number" name="weight" id="userWeight" class="form-control" aria-describedby="weightHelp" />
                    <div id="weightHelp" class="form-text"> กรอกน้ำหนักของคุณในหน่วยกิโลกรัม </div>
                </div>
                <div class="mb-3">
                    <label for="userHeight" class="form-label">ส่วนสูง (cm)</label>
                    <input type="number" name="height" id="userHeight" class="form-control" aria-describedby="heightHelp" />
                    <div id="heightHelp" class="form-text"> กรอกส่วนสูงของคุณในหน่วยเซนติเมตร </div>
                </div>
                <div class="mb-3">
                    <label for="userAge" class="form-label"> อายุ </label>
                    <input type="number" name="age" id="userAge" class="form-control" />
                </div>
                <button type="submit" class="btn btn-default btn-lg button-color"> คำนวณ </button>
            </form>
        </div>
    </div>
</div>

Views/Foods/BMRResult.cshtml
@model IEnumerable<FoodApp.Models.Food>

@{
	ViewData["Title"] = "Your BMR";
}

<h1 class="text-center heading-color"> ค่า BMR ของคุณคือ </h1>

<h2 class="text-center heading-color mt-5"> @ViewBag.Result </h2>
<h3 class="text-center heading-color"> 
    น้ำหนัก: @ViewBag.Weight kg ส่วนสูง: @ViewBag.Height cm <br />
    เพศ: @ViewBag.Age อายุ: @ViewBag.Gender 
</h3>

<h1 class="text-center heading-color mt-5"> Recommended Food </h1>

<div class="row mt-2">

    @foreach (var item in Model)
    {
        <div class="col-sm mt-2">
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <img src="@Html.DisplayFor(model => item.FoodImg)" class="card-img-top" style="height: 200px; width: auto;">
                    <div class="card-body">
                    <h5 class="card-title"> @Html.DisplayFor(modelItem => item.FoodName) </h5>
                    <p class="card-text"> 
                        @Html.DisplayFor(modelItem => item.FoodDesc) <br /> 
                        @Html.DisplayFor(modelItem => item.FoodCost) บาท <br />
                        @Html.DisplayFor(modelItem => item.FoodCal) kcal
                    </p>
                    </div>
                </div> 
            </div>  
        </div>
    }

</div>

Views/Foods/Create.cshtml
@model FoodApp.Models.Food

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Food</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FoodName" class="control-label"></label>
                <input asp-for="FoodName" class="form-control" />
                <span asp-validation-for="FoodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodImg" class="control-label"></label>
                <input asp-for="FoodImg" class="form-control" />
                <span asp-validation-for="FoodImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodDesc" class="control-label"></label>
                <input asp-for="FoodDesc" class="form-control" />
                <span asp-validation-for="FoodDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodCost" class="control-label"></label>
                <input asp-for="FoodCost" class="form-control" />
                <span asp-validation-for="FoodCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodCal" class="control-label"></label>
                <input asp-for="FoodCal" class="form-control" />
                <span asp-validation-for="FoodCal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Foods/Delete.cshtml
@model FoodApp.Models.Food

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Food</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FoodName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FoodDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FoodCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FoodCost)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Foods/Details.cshtml
@model FoodApp.Models.Food

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center heading-color">Details</h1>

<div class="row bg-light bg-gradient">
    <div class="col">
        <img src="@Html.DisplayFor(model => model.FoodImg)" class="img-fluid">
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                ชื่อเมนู <br/> @Html.DisplayFor(model => model.FoodName) 
            </div>
        </div>
        <div class="row">
            <div class="col">
                ส่วนผสม <br/> @Html.DisplayFor(model => model.FoodDesc) 
            </div>
        </div>
    </div>
</div>

<div class="row bg-light bg-gradient">
    <div class="col">
        ราคา <br/> @Html.DisplayFor(model => model.FoodCost)
    </div>
    <div class="col">
        แคลอรี่ <br/> @Html.DisplayFor(model => model.FoodCal)
    </div>
</div>

<div>
    <a href="/Foods/RandomFood/"> สุ่มอีกครั้ง </a>
</div>

Views/Foods/Edit.cshtml
@model FoodApp.Models.Food

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Food</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FoodName" class="control-label"></label>
                <input asp-for="FoodName" class="form-control" />
                <span asp-validation-for="FoodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodImg" class="control-label"></label>
                <input asp-for="FoodImg" class="form-control" />
                <span asp-validation-for="FoodImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodDesc" class="control-label"></label>
                <input asp-for="FoodDesc" class="form-control" />
                <span asp-validation-for="FoodDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodCost" class="control-label"></label>
                <input asp-for="FoodCost" class="form-control" />
                <span asp-validation-for="FoodCost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodCal" class="control-label"></label>
                <input asp-for="FoodCal" class="form-control" />
                <span asp-validation-for="FoodCal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Foods/Index.cshtml
@model IEnumerable<FoodApp.Models.Food>

@{
    ViewData["Title"] = "Food List";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FoodName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodDesc)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FoodName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FoodCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FoodDesc)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Foods/RandomFood.cshtml
@model IEnumerable<FoodApp.Models.Food>

@{
    ViewData["Title"] = "Random";
}

<div class="row">
    <div class="d-flex justify-content-center">
        <div class="card text-center">            
            <div class="card-body">
                <h5 class="card-title"> <strong>What to eat today?</strong> </h5>
                <form asp-action="RandomResult">
                    <button type="submit" name="randomPhrase" class="btn btn-default btn-lg button-color" value=@ViewBag.RandomValue> Random </button>
                </form>
            </div>           
        </div>
    </div>
</div>

Views/Foods/RandomResult.cshtml
@model IEnumerable<FoodApp.Models.Food>

@{
    ViewData["Title"] = "Result";
}

<h1 class="text-center heading-color"> Your Food is!! </h1>

<div class="row mt-2">

    @foreach (var item in Model)
    {
        <div class="col-sm mt-2">
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <img src="@Html.DisplayFor(model => item.FoodImg)" class="card-img-top" style="height: 200px; width: auto;">
                    <div class="card-body">
                    <h5 class="card-title"> @Html.DisplayFor(modelItem => item.FoodName) </h5>
                    <p class="card-text"> @Html.DisplayFor(modelItem => item.FoodDesc) <br /> @Html.DisplayFor(modelItem => item.FoodCost) </p>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary"> Food Details </a>
                    <a href="/Foods/RandomFood/" class="btn btn-primary"> Random Again </a>
                    </div>
                </div> 
            </div>  
        </div>
    }

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="row">
    <div class="d-flex justify-content-center">
        <div class="card text-center card-decor">            
            <h5 class="card-header">Welcome!</h5>
            <div class="card-body">
                <h5 class="card-title"> Random your menu for today </h5>
                <p class="card-text"> Don't know what to eat for today? let's random it! </p>
                <img src="~/images/smile_face.svg" alt="smile face" class="image-size mt-3 mb-3"> <br />
                <a href="/Foods/RandomFood/" class="btn btn-primary button-color"> Random Now </a>
            </div>           
        </div>

        <div class="card text-center card-decor mx-5">            
            <h5 class="card-header">Know your BMR</h5>
            <div class="card-body">
                <h5 class="card-title"> How to eat? </h5>
                <p class="card-text"> Don't know what to eat for today? let's random it! </p>
                <img src="~/images/smile_face.svg" alt="smile face" class="image-size mt-3 mb-3"> <br />
                <a href="/Foods/BMRForm/" class="btn btn-primary button-color"> Calculated </a>
            </div>           
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Foods" asp-action="Index">FoodApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer footer-text">
        <div class="container">
            &copy; 2022 - FoodApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>